var categories = [
{"name":"Accounting/Finance","shortName":"Accounting","id":"1"},
{"name":"Administrative","shortName":"Administrative","id":"2"},
{"name":"Analyst","shortName":"Analyst","id":"3"},
{"name":"Architecture/Drafting","shortName":"Architecture","id":"4"},
{"name":"Art/Design/Entertainment","shortName":"Design","id":"5"},
{"name":"Banking/Loan/Insurance","shortName":"Banking","id":"6"},
{"name":"Beauty/Wellness","shortName":"Beauty","id":"7"},
{"name":"Business Development/Consulting","shortName":"Business Development","id":"8"},
{"name":"Education","shortName":"Education","id":"9"},
{"name":"Engineering (Non-software)","shortName":"Engineering","id":"10"},
{"name":"Facilities/General Labor","shortName":"Facilities","id":"11"},
{"name":"Hospitality","shortName":"Hospitality","id":"12"},
{"name":"Human Resources","shortName":"Human Resources","id":"13"},
{"name":"Installation/Maintenance/Repair","shortName":"Maintenance","id":"14"},
{"name":"Legal","shortName":"Legal","id":"15"},
{"name":"Manufacturing/Production/Construction","shortName":"Construction","id":"16"},
{"name":"Marketing/Advertising/PR","shortName":"Marketing","id":"17"},
{"name":"Medical/Healthcare","shortName":"Medical","id":"18"},
{"name":"Non-Profit/Volunteering","shortName":"Volunteering","id":"19"},
{"name":"Product/Project Management","shortName":"Project Management","id":"20"},
{"name":"Real Estate","shortName":"Real Estate","id":"21"},
{"name":"Restaurant/Food Services","shortName":"Restaurant","id":"22"},
{"name":"Retail","shortName":"Retail","id":"23"},
{"name":"Sales/Customer Care","shortName":"Sales","id":"24"},
{"name":"Science/Research","shortName":"Research","id":"25"},
{"name":"Security/Law Enforcement","shortName":"Security","id":"26"},
{"name":"Senior Management","shortName":"Senior Management","id":"27"},
{"name":"Skilled Trade","shortName":"Skilled Trade","id":"28"},
{"name":"Software Development/IT","shortName":"Software Development","id":"29"},
{"name":"Sports/Fitness","shortName":"Sports","id":"30"},
{"name":"Travel/Transportation","shortName":"Transportation","id":"31"},
{"name":"Writing/Editing/Publishing","shortName":"Writing","id":"32"},
{"name":"Other","shortName":"Other","id":"33"}
];